<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Pitiass-MBP.fios-router.home" name="take.homw.script.Script" tests="18" failures="2" timestamp="2020-09-19T12:22:24 EDT" time="250.358" errors="0">
  <testcase name="login_Success" time="13.486" classname="take.homw.script.Script"/>
  <system-out/>
  <testcase name="login_fail" time="7.496" classname="take.homw.script.Script">
    <failure type="java.lang.AssertionError" message="expected [http://localhost:7080/secure] but found [http://localhost:7080/login]">
      <![CDATA[java.lang.AssertionError: expected [http://localhost:7080/secure] but found [http://localhost:7080/login]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at gmail.pitias4work.com.Login_failer.login_fail(Login_failer.java:37)
at take.homw.script.Script.login_fail(Script.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- login_fail -->
  <system-out/>
  <testcase name="checkbox" time="7.260" classname="take.homw.script.Script"/>
  <system-out/>
  <testcase name="context_menu" time="10.338" classname="take.homw.script.Script"/>
  <system-out/>
  <testcase name="dragandDrop" time="28.603" classname="take.homw.script.Script"/>
  <system-out/>
  <testcase name="dropDown" time="9.329" classname="take.homw.script.Script"/>
  <system-out/>
  <testcase name="dynamic_Content" time="19.801" classname="take.homw.script.Script">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at gmail.pitias4work.com.DynamicContent.dynamic_Content(DynamicContent.java:36)
at take.homw.script.Script.dynamic_Content(Script.java:68)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- dynamic_Content -->
  <system-out/>
  <testcase name="dynamic_Control" time="27.191" classname="take.homw.script.Script"/>
  <system-out/>
  <testcase name="dynamic_Loading" time="16.247" classname="take.homw.script.Script"/>
  <system-out/>
  <testcase name="fileDownload" time="14.214" classname="take.homw.script.Script"/>
  <system-out/>
  <testcase name="fileUpload" time="12.370" classname="take.homw.script.Script"/>
  <system-out/>
  <testcase name="floating_Menu" time="8.815" classname="take.homw.script.Script"/>
  <system-out/>
  <testcase name="iframe" time="8.445" classname="take.homw.script.Script"/>
  <system-out/>
  <testcase name="mouse_Hover" time="15.642" classname="take.homw.script.Script"/>
  <system-out/>
  <testcase name="javaScriptAlerts" time="14.956" classname="take.homw.script.Script"/>
  <system-out/>
  <testcase name="JavaScriptError" time="6.030" classname="take.homw.script.Script"/>
  <system-out/>
  <testcase name="openNewTab" time="9.285" classname="take.homw.script.Script"/>
  <system-out/>
  <testcase name="notification_Msg" time="20.850" classname="take.homw.script.Script"/>
  <system-out/>
</testsuite> <!-- take.homw.script.Script -->
