<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-PD0G2153" failures="1" tests="6" name="tests.DynamicContentTest" time="53.191" errors="0" timestamp="2022-12-16T17:09:37 EST" skipped="0">
  <testcase classname="tests.DynamicContentTest" name="CheckDynamicPicture3" time="7.339">
    <failure message="did not expect [http://localhost:7080/img/avatars/Original-Facebook-Geek-Profile-Avatar-3.jpg] but found [http://localhost:7080/img/avatars/Original-Facebook-Geek-Profile-Avatar-3.jpg]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: did not expect [http://localhost:7080/img/avatars/Original-Facebook-Geek-Profile-Avatar-3.jpg] but found [http://localhost:7080/img/avatars/Original-Facebook-Geek-Profile-Avatar-3.jpg]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at org.testng.Assert.assertNotEquals(Assert.java:1535)
at tests.DynamicContentTest.CheckDynamicPicture3(DynamicContentTest.java:88)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- CheckDynamicPicture3 -->
  <system-out/>
  <testcase classname="tests.DynamicContentTest" name="CheckDynamicText2" time="6.137"/>
  <system-out/>
  <testcase classname="tests.DynamicContentTest" name="CheckDynamicPicture1" time="13.777"/>
  <system-out/>
  <testcase classname="tests.DynamicContentTest" name="CheckDynamicText1" time="4.372"/>
  <system-out/>
  <testcase classname="tests.DynamicContentTest" name="CheckDynamicPicture2" time="12.371"/>
  <system-out/>
  <testcase classname="tests.DynamicContentTest" name="CheckDynamicText3" time="9.195"/>
  <system-out/>
</testsuite> <!-- tests.DynamicContentTest -->
